#include "../utility.h"
#include "../displayDriver.h"
#include "../interruptRequests.h"
#include "../timerHandler.h"

int totalSystemTicks = 0;
int totalTimeInSeconds = 0;
int timer_tick_request = -1;
int requestPending = 0 ;

void initialize_Timer()
{

}

// Handles the periodic interrupt generated by PIC
void timerInterruptHandlingRoutine(registerStructure *r)
{
    totalSystemTicks++;

	// 18.02 Hz is the default firing frequency of timer interrupts
    if (totalSystemTicks % 18 == 0 && 1 == requestPending)
    {      
        totalTimeInSeconds ++ ;
        setTextColor(eCyan);
        putStringOnScreen("\nTimer triggered.");
	
		if( timer_tick_request == totalTimeInSeconds )
		{
		  putStringOnScreen("\nTimer expired.\n");
		  requestPending = 0 ;          
		}
    }
}

// Initializes the timer with input number of seconds
void startTimer(unsigned int time)
{
    timer_tick_request = time + totalTimeInSeconds ;
    requestPending = 1;
    setTextColor(eWhite);
    putStringOnScreen("\n\nStart timer requested. \n");
}

